/**
 * MERQO centralized terminology glossary (বাংলা).
 *
 * Single source of truth for product terminology (§123). Every screen must
 * take its canonical labels from here so the product never mixes
 * translations inconsistently.
 *
 * Canonical decisions:
 *  - Customer  → কাস্টমার (not গ্রাহক)
 *  - Supplier  → সাপ্লায়ার (not সরবরাহকারী)
 *  - Inventory → ইনভেন্টরি (module), স্টক (stock quantity)
 *  - Credit    → উজড় (credit sale = উজড় বিক্রয়)
 */
export const T = {
  // Modules
  dashboard: 'ড্যাশবোর্ড',
  pos: 'বিক্রয় / POS',
  products: 'পণ্য',
  inventory: 'ইনভেন্টরি',
  purchases: 'ক্রয়',
  salesHistory: 'বিক্রয় ইতিহাস',
  customers: 'কাস্টমার',
  suppliers: 'সাপ্লায়ার',
  expenses: 'খরচ',
  accounts: 'হিসাব',
  mfsAgent: 'MFS এজেন্ট',
  reports: 'রিপোর্ট',
  invoices: 'ইনভয়েস',
  notifications: 'নোটিফিকেশন',
  usersSecurity: 'ব্যবহারকারী ও নিরাপত্তা',
  backup: 'ব্যাকআপ',
  settings: 'সেটিংস',
  setup: 'সেটআপ',
  login: 'লগইন',

  // Domain nouns
  product: 'পণ্য',
  category: 'ক্যাটাগরি',
  brand: 'ব্র্যান্ড',
  unit: 'একক',
  price: 'দাম',
  quantity: 'পরিমাণ',
  barcode: 'বারকোড',
  sku: 'SKU',
  batch: 'ব্যাচ',
  expiry: 'মেয়াদ শেষ',
  stock: 'স্টক',
  stockValue: 'স্টক মূল্য',
  sale: 'বিক্রয়',
  purchase: 'ক্রয়',
  return: 'ফেরত',
  customer: 'কাস্টমার',
  supplier: 'সাপ্লায়ার',
  due: 'বকেয়া',
  payable: 'প্রদেয়',
  receivable: 'প্রাপ্য',
  profit: 'লাভ',
  grossProfit: 'মূল লব্ধি',
  netProfit: 'নিট লাভ',
  loss: 'ক্ষতি',
  expense: 'খরচ',
  cash: 'নগদ',
  bank: 'ব্যাংক',
  payment: 'পেমেন্ট',
  receipt: 'রসিদ',
  invoice: 'ইনভয়েস',
  report: 'রিপোর্ট',
  shift: 'শিফট',
  agent: 'এজেন্ট',
  commission: 'কমিশন',
  transfer: 'ট্রান্সফার',
  discount: 'ছাড়',
  tax: 'কর',
  vat: 'ভ্যাট',
  credit: 'উজড়',
  advance: 'অগ্রিম',
  note: 'নোট',
  reference: 'রেফারেন্স',
  reason: 'কারণ',
  status: 'অবস্থা',
  date: 'তারিখ',
  time: 'সময়',
  total: 'মোট',
  subtotal: 'আংশিক মোট',
  grandTotal: 'সর্বমোট',
  paid: 'প্রদত্ত',
  change: 'ফেরত অর্থ',
  remaining: 'বাকি',
  margin: 'মার্জিন',
  cost: 'খরচদাম',
  sellingPrice: 'বিক্রয় মূল্য',
  purchasePrice: 'ক্রয় মূল্য',
  wholesalePrice: 'হোলসেল মূল্য',
  minPrice: 'ন্যূনতম মূল্য',
  openingStock: 'প্রাথমিক স্টক',
  reorderLevel: 'পুনরায় অর্ডার সীমা',

  // Common actions
  save: 'সংরক্ষণ করুন',
  cancel: 'বাতিল করুন',
  confirm: 'নিশ্চিত করুন',
  delete: 'মুছুন',
  edit: 'সম্পাদনা',
  add: 'যোগ করুন',
  search: 'খুঁজুন',
  print: 'প্রিন্ট করুন',
  exportPdf: 'PDF হিসেবে সংরক্ষণ করুন',
  exportCsv: 'CSV হিসেবে ডাউনলোড করুন',
  complete: 'সম্পন্ন করুন',
  view: 'দেখুন',
  back: 'ফিরে যান',
  next: 'পরবর্তী',
  previous: 'পূর্ববর্তী',
  finish: 'শেষ করুন',
  retry: 'আবার চেষ্টা করুন',
  close: 'বন্ধ করুন',
  open: 'খুলুন',
  yes: 'হ্যাঁ',
  no: 'না',
  all: 'সব',
  today: 'আজ',
  loading: 'লোড হচ্ছে…',
  noData: 'কোনো তথ্য নেই',
  actions: 'অ্যাকশন',
  details: 'বিস্তারিত',

  // POS
  newSale: 'নতুন বিক্রয়',
  completeSale: 'বিক্রয় সম্পন্ন করুন',
  holdSale: 'বিক্রয় হোল্ড করুন',
  resumeSale: 'হোল্ড বিক্রয়',
  walkInCustomer: 'সাধারণ কাস্টমার',
  creditSale: 'উজড় বিক্রয়',
  takePayment: 'পেমেন্ট গ্রহণ করুন',
  barcodeNotFound: 'এই বারকোডের কোনো পণ্য পাওয়া যায়নি।',
  cartEmpty: 'কার্ট খালি',

  // Statuses (§116 — icon + label + subtle color, never color alone)
  stPaid: 'পরিশোধিত',
  stPartial: 'আংশিক পরিশোধিত',
  stDue: 'বকেয়া',
  stOverdue: 'অতিরিক্ত বকেয়া',
  stCancelled: 'বাতিল',
  stRefunded: 'ফেরত প্রদান',
  stVoided: 'বিলগা',
  stCompleted: 'সম্পন্ন',
  stActive: 'সক্রিয়',
  stInactive: 'নিষ্ক্রিয়',
  stLowStock: 'কম স্টক',
  stOutOfStock: 'স্টক শেষ',
  stExpiring: 'মেয়াদ প্রায় শেষ',
  stExpired: 'মেয়াদোত্তীর্ণ',
  stDamaged: 'ক্ষতিগ্রস্ত'
} as const;

export type TermKey = keyof typeof T;
